#!/bin/bash
curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
yum install nano composer git nodejs libpng* -y

# Rclone
curl https://rclone.org/install.sh | sudo bash

# letsencrypt
git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
service nginx stop
cd /opt/letsencrypt
./letsencrypt-auto certonly --standalone
